#!/bin/bash

NOW=$(date '+%Y-%m-%d %H:%M:%S')
TIMESTAMP=$(($(date +%s%N)/1000000))
PERF=$(ps -C PalServer-Linux -o %cpu,%mem,vsz,rss --no-headers | awk ' {OFS=","; print $1,$2,$3,$4 }')

if pgrep PalServer-Linux; then
    echo "$NOW,running,$PERF" >> /home/steam/log/palserver.csv
else
    echo "$NOW,restarting,0,0,0,0" >> /home/steam/log/palserver.csv
    mv "/home/steam/log/palserver.csv" /home/steam/log/crashes/palserver-$TIMESTAMP.csv
    s3cmd put -r /home/steam/log/crashes/ s3://$BUCKET_NAME/
    rm /home/steam/log/crashes/*
    curl $HOOK >/dev/null 2>&1
    /bin/bash /home/steam/Palworld/PalServer.sh >/dev/null 2>&1
fi
