#!/bin/bash

tail -n1440 /home/steam/log/palserver.csv > /home/steam/log/palserver-temp.csv
mv /home/steam/log/palserver-temp.csv /home/steam/log/palserver.csv
s3cmd put -r /home/steam/log/palserver.csv s3://$BUCKET_NAME/perf/
curl $HOOK >/dev/null 2>&1
